config/routes.rb
Rails.application.routes.draw do
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'

  get 'sign_up' => 'users#new', :as => 'sign_up'
  root :to => 'sessions#new'
  get 'profile', to: 'sessions#show', :as => 'profile'

  resources :users do
    resources :rsvps
  end

  resources :sessions

  resources :artists, :path => '/artists'
  resources :events, :path => '/events'
  resources :venues
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ARTISTS<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @artists.each do |artist| %>
              <li><%= link_to artist.name, artist %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">EVENTS<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/events">See all events</a></li>
            <li><a href="/events/new">Add an event</a></li>
          </ul>
        </li>
      </ul>
				
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <div id="user_nav">
      <ul class="nav navbar-nav navbar-right">
			<% if current_user.guest? %>
        <li><%= "Make sure to " %></li>
        <li><%= link_to "Log in", log_in_path %></li>
        <li><%= "or" %></li>
        <li><%= link_to "Sign up", sign_up_path %></li>
        <li><%= "before your guest session expires" %></li>
      <% else %>
				<li><%= link_to current_user.username, profile_path %>
				</li>
        <li><%= link_to "(sign out)", log_out_path %></li>
      <% end %>
      </ul>
      </div>
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_rsvps.html.erb
<%= form_for [current_user, rsvp], remote: true do |f| %>
	<%= f.hidden_field :event_id %>
	<%= f.radio_button :status, "attending", :onclick => "this.form.submit();" %>
	<%= f.radio_button :status, "interested", :onclick => "this.form.submit();"%>
	<%= f.radio_button :status, "not_interested", :onclick => "this.form.submit();" %>
<% end %>