config/routes.rb
Rails.application.routes.draw do
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'

  get 'sign_up' => 'users#new', :as => 'sign_up'
  root :to => 'sessions#new'
  get 'profile', to: 'sessions#show', :as => 'profile'

  resources :users do
    resources :rsvps
  end

  resources :sessions

  resources :artists, :path => '/artists'
  resources :events, :path => '/events'
  resources :venues
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  has_many :event_artists
  has_many :artists, through: :event_artists
  has_many :rsvps
  has_many :users, through: :rsvps
#  accepts_nested_attributes_for :event_artists, reject_if: :all_blank, allow_destroy: true

# scope :for_event, ->(event) { where(:event_id => event.id) }

  def title
    "#{self.name} with #{self.artists.map(&:name).join(", ")} at #{self.venue.name}"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :update, :destroy]

  # GET /events
  def index
    @events = Event.all

   # render json: @events
  end

  # GET /events/1
  def show
    @event = Event.find(params[:id])
    @rsvp = @event.rsvps.find_or_initialize_by user: current_user if current_user
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      render json: @event, status: :created, location: @event
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end

  def new
    @event = Event.new
    @artist = @event.event_artists.build
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      render json: @event
    else
      render :new
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:id, :name, :date, :venue_id, :description, artist_ids: [])
    end
end

app/views/events/index.html.erb
<% @events.each do |event| %> <tr>
    <td><%= link_to event.name, event_path(event) %></td>
    <td><%= "on" %></td>
    <td><%= event.date %></td>
    <td>
      <ul>
				<% event.artists.each do |artist| %></td>
					<li><%= artist.name %></li>
				<% end %>
      </ul>
    </td>
  </tr>
<% end %>

app/views/events/new.html.erb
<%= form_for @event, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :name %><br />
  <%= f.datetime_select :date %><br />
  <%= f.text_area :description, size: "60x12" %><br />
  <%= f.select(
    :venue_id,
    options_from_collection_for_select(Venue.all, "id", "name")
  ) %>
  <%= f.select(:artist_ids, Artist.all.collect {|a| [a.name, a.id]}, {}, id: "event_artist_ids", :multiple => true) %>
  <br />
  <%= f.submit "Create" %><br />

<% end %>
	<script type="text/javascript">
    $( "#event_artist_ids" ).select2();
	</script>

app/views/events/show.html.erb
<div class="container">
  <div class="jumbotron">
    <td><%= @event.name %></td>
    <td><%= "on" %></td>
    <td><%= @event.date %></td>
    <td>
      <ul>
				<% @event.artists.each do |artist| %></td>
					<li><%= artist.name %></li>
				<% end %>
      </ul>
    </td>
    <td>
      <% if @rsvp %>
        <%= render partial: "shared/rsvps", locals: { rsvp: @rsvp }, html: { class: ["new", "update"] } %>
      <% end %>
    </td>
  </div>
</div>